### ISSUE TITLE
instructions should be more explicit that youre writing a setter/getter

### ISSUE THREAD

**Issue by TOMalley104** [learn-co-curriculum/oo-sentence#16]
students are just creating properties instead and then wondering what the lab means when it tells them to create an instance variable

**Comment by AnnJohn** [comment]
Iceboxing until lab is used again

**Comment by markedwardmurray** [comment]
that lab has been rewritten into https://github.com/learn-co-curriculum/objc-fissentence . This repository is now deprecated.
